### ISSUE TITLE
Duplicate `version_option` raises `AssertionError`

### ISSUE THREAD

**Issue by rasa** [kdeldycke/click-extra#317]
With click-extra 3.4.0, the script at https://kdeldycke.github.io/click-extra/commands.html#default-options :
```python
from click_extra import extra_command, version_option, config_option, verbosity_option

@extra_command()
@version_option(version="0.1")
@config_option(default="ex.yml")
@verbosity_option(default="DEBUG")
def cli():
   pass
cli()
```
produces:
```text
debug: Verbosity set to DEBUG.
Traceback (most recent call last):
  File "C:\issue317.py", line 9, in <module>
    cli()
  File "C:\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click_extra\commands.py", line 161, in main
    return super().main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click_extra\commands.py", line 203, in invoke
    version_param = self._get_param(ctx, VersionOption)
  File "C:\Python310\lib\site-packages\click_extra\commands.py", line 189, in _get_param
    assert len(params) == 1
AssertionError
```
Commenting out the `@version_option` fixes it:
```python
from click_extra import extra_command, version_option, config_option, verbosity_option

@extra_command()
# @version_option(version="0.1")
@config_option(default="ex.yml")
@verbosity_option(default="DEBUG")
def cli():
   pass
cli()
```
produces:
```text
debug: Verbosity set to DEBUG.
debug: issue317.py, version 3.4.0
```
Note that the script:
```python
from click_extra import extra_command, VersionOption, ConfigOption, VerbosityOption
@extra_command(params=[
   VersionOption(version="0.1"),
   ConfigOption(default="ex.yml"),
   VerbosityOption(default="DEBUG"),
])
def cli():
   pass
cli()
```
works as expected:
```text
debug: Verbosity set to DEBUG.
debug: issue317.py, version 0.1
```

**Comment by kdeldycke** [comment]
I confirm the issue with the upstream version of `click-extra`:
```python
$ poetry run python ./issue317.py
debug: Verbosity set to DEBUG.
Traceback (most recent call last):
  File "~/click-extra/./issue317.py", line 9, in <module>
    cli()
  File "~/click-extra/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/click-extra/click_extra/commands.py", line 244, in main
    return super().main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/click-extra/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "~/click-extra/click_extra/commands.py", line 291, in invoke
    version_param = self._get_param(ctx, VersionOption)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/click-extra/click_extra/commands.py", line 277, in _get_param
    assert len(params) == 1
           ^^^^^^^^^^^^^^^^
AssertionError
```

It boils down to the fact that you are adding via decorators options that are already pre-registered in `@extra_command`. You can check that out in the help screen:
```shell-session
$ poetry run python ./issue317.py --help
Usage: truc.py [OPTIONS]

Options:
  --time / --no-time        Measure and print elapsed execution time.  [default:
                            no-time]
  --color, --ansi / --no-color, --no-ansi
                            Strip out all colors and all ANSI codes from output.
                            [default: color]
  -C, --config CONFIG_PATH  Location of the configuration file. Supports glob
                            pattern of local path and remote URL.  [default:
                            ~/Library/Application
                            Support/truc.py/*.{toml,yaml,yml,json,ini,xml}]
  --show-params             Show all CLI parameters, their provenance, defaults
                            and value, then exit.
  -v, --verbosity LEVEL     Either CRITICAL, ERROR, WARNING, INFO, DEBUG.
                            [default: INFO]
  --version                 Show the version and exit.
  -h, --help                Show this message and exit.
  --version                 Show the version and exit.
  -C, --config CONFIG_PATH  Location of the configuration file. Supports glob
                            pattern of local path and remote URL.  [default:
                            ex.yml]
  -v, --verbosity LEVEL     Either CRITICAL, ERROR, WARNING, INFO, DEBUG.
                            [default: DEBUG]
```

This is documented at: https://kdeldycke.github.io/click-extra/commands.html#change-default-options

**Comment by kdeldycke** [comment]
That being said, to make things clearer, Click Extra will now raise an explicit error if you defines multiple `--version` options.
